services:
  frontend:
    image: node:lts-alpine
    working_dir: /frontend
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules
    ports:
      - "5173:5173"
    command: sh -c "npm install && npm run dev -- --host"

  backend:
    image: node:lts-alpine
    working_dir: /server
    volumes:
      - ./server:/server
      - /server/node_modules
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgres://veggie-user:HmxWFa4EgEYJnjs7ABdLRELS4fpv86vL@veggie-database:5432/veggie-db
      - CORS_URL=http://localhost:5173
    depends_on:
      veggie-database:
        condition: service_healthy
    command: sh -c "npm install && node server.js"

  veggie-database:
    container_name: veggie-database
    image: postgres:13-alpine
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=veggie-user
      - POSTGRES_PASSWORD=HmxWFa4EgEYJnjs7ABdLRELS4fpv86vL
      - POSTGRES_DB=veggie-db
    volumes:
      - veggie-database-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U veggie-user -d veggie-db"]
      interval: 5s
      timeout: 5s
      retries: 5

  veggie-database-viewer:
    container_name: veggie-database-viewer
    image: dpage/pgadmin4
    ports:
      - "54320:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@example.com
      - PGADMIN_DEFAULT_PASSWORD=g3KyPSr26tgKmyWbGb4MrSmGm5c5rg8T

volumes:
  veggie-database-data:
    name: veggie-database-data
